#------------------------------------------------------------------------------
# CSparse Makefile
#------------------------------------------------------------------------------

all:
	( cd Lib ; $(MAKE) )

clean: # removes all object files
	( cd Lib ; $(MAKE) clean )

purge: # removes everything compiled, linked, archived, etc
	( cd Lib ; $(MAKE) purge )

